services:
  db-webschool:
    image: postgres
    network_mode: 
      bridge
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test

  pgadmin:
    image: dpage/pgadmin4
    ports:
    - 8080:80
    network_mode:
      bridge
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
        PGADMIN_DEFAULT_PASSWORD: password
        PGADMIN_LISTEN_PORT: 80
    depends_on:
        - db-webschool